name: Unity Compile Check

on:
  pull_request:
    branches: [ main, Development ]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: game-ci/unity-builder@v4
        with:
          unityVersion: 6000.2.2f1
          targetPlatform: StandaloneWindows64
