name: Unity Compile Check

on:
  pull_request:
    branches: [ main, Development ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - uses: game-ci/unity-test-runner@v4
        with:
          unityVersion: 6000.2.2f1
          testMode: editmode
