name: Unity Build

on:
  pull_request:
    branches: [ main, Development ]

jobs:
  compile:
    runs-on: ubuntu-latest

    env:
      UNITY_DISABLE_LICENSE: true

    steps:
      - uses: actions/checkout@v4

      - uses: game-ci/unity-test-runner@v4
        with:
          unityVersion: 6000.2.2f1
          testMode: editmode
